/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package necorlibsys;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
/**
 *
 * @author mexen
 */
public class PatronsMenu extends javax.swing.JDialog {

    /**
     * Creates new form PatronsMenu
     * @param parent
     * @param modal
     */
    public PatronsMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButtonAddPatron = new javax.swing.JButton();
        jTextFirstName = new javax.swing.JTextField();
        jTextInitial = new javax.swing.JTextField();
        jTextLastName = new javax.swing.JTextField();
        jTextAddress = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jTextPhone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jFormattedTextDOB = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextEditPatID = new javax.swing.JTextField();
        jButtonEditSearch = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonEditSave = new javax.swing.JButton();
        jTextEditFirstName = new javax.swing.JTextField();
        jTextEditInitial = new javax.swing.JTextField();
        jTextEditLastName = new javax.swing.JTextField();
        jTextEditAddress = new javax.swing.JTextField();
        jTextEditEmail = new javax.swing.JTextField();
        jTextEditPhone = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jFormattedEditDOB = new javax.swing.JFormattedTextField();
        jComboBoxEditGender = new javax.swing.JComboBox<>();
        jButtonEditClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextDeletePatID = new javax.swing.JTextField();
        jButtonDeleteSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextDeleteAddress = new javax.swing.JTextField();
        jTextDeleteLastName = new javax.swing.JTextField();
        jTextDeleteInitial = new javax.swing.JTextField();
        jTextDeleteFirstName = new javax.swing.JTextField();
        jTextDeleteEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextDeletePhone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jFormattedDeleteDOB = new javax.swing.JFormattedTextField();
        jComboBoxDeleteGender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pat.png"))); // NOI18N

        jLabel2.setText("Manage Library Patrons");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("First Name:");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Initial:");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Last Name:");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Address:");

        jButtonAddPatron.setText("Add");
        jButtonAddPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPatronActionPerformed(evt);
            }
        });

        jTextInitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextInitialActionPerformed(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("E-mail:");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Phone:");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("DoB:");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Gender:");

        jComboBoxGender.setMaximumRowCount(2);
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenderActionPerformed(evt);
            }
        });

        jFormattedTextDOB.setToolTipText("YYYY-MM-DD");
        jFormattedTextDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextDOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel21))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAddPatron))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 141, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFirstName, jTextLastName});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddPatron)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add", jPanel1);

        jLabel10.setText("Patron ID:");

        jButtonEditSearch.setText("Search");
        jButtonEditSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSearchActionPerformed(evt);
            }
        });

        jLabel11.setText("First Name:");

        jLabel12.setText("Initial:");

        jLabel13.setText("Last Name:");

        jLabel14.setText("Address:");

        jLabel15.setText("E-mail:");

        jLabel16.setText("Phone:");

        jButtonEditSave.setText("Save");
        jButtonEditSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSaveActionPerformed(evt);
            }
        });

        jLabel25.setText("DoB:");

        jLabel26.setText("Gender:");

        jComboBoxEditGender.setMaximumRowCount(2);
        jComboBoxEditGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jComboBoxEditGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEditGenderActionPerformed(evt);
            }
        });

        jButtonEditClear.setText("Clear");
        jButtonEditClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextEditPatID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextEditAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jButtonEditClear))
                            .addComponent(jTextEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedEditDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEditGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEditInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEditPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditSave)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextEditFirstName, jTextEditLastName});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextEditPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jTextEditInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEditPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jFormattedEditDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jComboBoxEditGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextEditAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditSave)
                            .addComponent(jButtonEditClear))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Edit", jPanel2);

        jLabel3.setText("Patron ID:");

        jButtonDeleteSearch.setText("Search");
        jButtonDeleteSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSearchActionPerformed(evt);
            }
        });

        jLabel4.setText("First Name:");

        jLabel5.setText("Initial:");

        jLabel6.setText("Last Name:");

        jLabel7.setText("Address:");

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel8.setText("E-mail:");

        jLabel9.setText("Phone:");

        jLabel27.setText("DoB:");

        jLabel28.setText("Gender:");

        jComboBoxDeleteGender.setMaximumRowCount(2);
        jComboBoxDeleteGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDelete))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextDeletePatID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDeleteSearch))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextDeleteFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jTextDeleteLastName)
                                    .addComponent(jTextDeleteInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextDeleteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDeletePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jFormattedDeleteDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDeleteGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDeleteAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextDeleteFirstName, jTextDeleteLastName});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextDeletePatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jTextDeleteFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDeleteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextDeleteInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jTextDeletePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextDeleteLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jFormattedDeleteDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jComboBoxDeleteGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextDeleteAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Delete", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Database
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/necorlibsys";
    
    static final String USER = "root";
    static final String PASS = "R00t.paribas";
    
    Connection conn = null;
    Statement stmt = null;
    PreparedStatement pStmt = null;
    
    // Get the entered data
    String patronID;
    
    String firstName; 
    String initial;
    String lastName;
    String address;
    String dob;
    String gender;
    String email;
    String phone;
    String insertPatron;
    String editPatron;
    String insertEditPatron;
    String deletePatron;
    String search;
    String male = "M";
    String female = "F";
    int status = 0; // for purposes of empty records
    
            
    
    // Add button inserts the new record to the database
    private void jButtonAddPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPatronActionPerformed
        // TODO add your handling code here:
        firstName = jTextFirstName.getText();
        initial = jTextInitial.getText().substring(0);
        lastName = jTextLastName.getText();
        dob = jFormattedTextDOB.getText();
        address = jTextAddress.getText();
        email = jTextEmail.getText();
        phone = jTextPhone.getText();
        
        if(jComboBoxGender.getSelectedItem().equals(male)){
            gender = male;
        } else {
            gender = female;
        }
        insertPatron = "INSERT INTO patron"+
                "(first_name,initial,last_name,dob,gender,address,email,phone)"+
                "VALUES"+
                "(\'"+firstName+"\',"+"\'"+initial+"\',"+"\'"+lastName+"\',"+
                "\'"+dob+"\',"+"\'"+gender+"\',"+
                "\'"+address+"\',"+"\'"+email+"\',"+"\'"+phone+"\'"+")";
        
        try{
        Class.forName(JDBC_DRIVER);
        }catch(ClassNotFoundException e){}
        try{
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        stmt = conn.createStatement();
        
        //warn user to enter something if field is empty
        if (((firstName.isEmpty() || lastName.isEmpty()) || (address.isEmpty() || phone.isEmpty())) || (email.isEmpty())){
           int warning = JOptionPane.showConfirmDialog(null, "Enter missing values.", "Warning",
            JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
        }
        
        else {
        // Prompt the user
        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Add this patron?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        // close dialog if no
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.getRootFrame().dispose();
            
        // add book if yes
        } else if (response == JOptionPane.YES_OPTION) {
        
        // insert the record
        stmt.executeUpdate(insertPatron);
        conn.close();
        
        // clear the text fields - use a method
        jTextFirstName.setText("");
        jTextInitial.setText("");
        jTextLastName.setText("");
        jFormattedTextDOB.setText("");
        jTextAddress.setText("");
        jTextEmail.setText("");
        jTextPhone.setText("");
        
       

        } 
            
        }  
        
        
        
        }catch(SQLException se){}
        
    }//GEN-LAST:event_jButtonAddPatronActionPerformed

    private void jFormattedTextDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextDOBActionPerformed

    private void jTextInitialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextInitialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextInitialActionPerformed

    private void jComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenderActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        gender = (String)cb.getSelectedItem();
      
    }//GEN-LAST:event_jComboBoxGenderActionPerformed
   
    // Search for a record to edit
    private void jButtonEditSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSearchActionPerformed
        // TODO add your handling code here:
        // Search for a record to edit
        
        //jTextEditFirstName.setText("Test");
        jButtonEditClearActionPerformed(evt);
        
        try{
        Class.forName(JDBC_DRIVER);
        }catch(ClassNotFoundException e){}
        try{
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        stmt = conn.createStatement();
        patronID = jTextEditPatID.getText();
        
        
        //warn user if ID has not been entered
        if(patronID.isEmpty()){ 
           int warning = JOptionPane.showConfirmDialog(null, "Please enter an ID.", "Attention.",
            JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
        }
        else{
                
        search = "SELECT * FROM patron WHERE patron_id = " + patronID + " ";
        ResultSet rs = stmt.executeQuery(search);
        
        while(rs.next()){
        jTextEditFirstName.setText(rs.getString("first_name"));
        jTextEditInitial.setText(rs.getString("initial"));
        jTextEditLastName.setText(rs.getString("last_name"));
        
        
        // Change date format
        DateFormat df;
            df = new SimpleDateFormat("yyyy-MM-dd");
        dob = df.format(rs.getDate("dob"));
        if (dob.isEmpty() || dob == null){
            jFormattedEditDOB.setText("");
        } else{
        jFormattedEditDOB.setText(dob);
        }
        
        jComboBoxEditGender.setSelectedItem(rs.getString("gender"));
        jTextEditAddress.setText(rs.getString("address"));
        jTextEditEmail.setText(rs.getString("email"));
        jTextEditPhone.setText(rs.getString("phone")); 
        
        } // end while
        
        
        String test = jTextEditFirstName.getText();
        if(test.isEmpty()){ 
           int warning = JOptionPane.showConfirmDialog(null, "No record found.", "Attention.",
            JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
           
           status = 1;
        }
        
        
        
        }
        conn.close();
        
        
        }catch(SQLException se){}
    }//GEN-LAST:event_jButtonEditSearchActionPerformed

    private void jComboBoxEditGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEditGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEditGenderActionPerformed

    
// Save the changes made to the record
    private void jButtonEditSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSaveActionPerformed
        // TODO add your handling code here:
        
        //patronID = jTextEditPatID.getText();
        int id = Integer.parseInt(patronID);
        firstName = jTextEditFirstName.getText();
        initial = jTextEditInitial.getText().substring(0);
        lastName = jTextEditLastName.getText();
        dob = jFormattedEditDOB.getText();
        if(jComboBoxEditGender.getSelectedItem().equals(male)){
            gender = male;
        } else {
            gender = female;
        }
        address = jTextEditAddress.getText();
        email = jTextEditEmail.getText();
        phone = jTextEditPhone.getText();
        editPatron = "UPDATE patron SET first_name = ?, initial = ?, last_name = ?, dob = ?, gender = ?, address = ?, email = ?, phone = ? WHERE patron_id = ?";
        
        try{
        Class.forName(JDBC_DRIVER);
        }catch(ClassNotFoundException e){}
        try{
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        stmt = conn.createStatement();
         
        
        //warn user to enter something if field is empty
        if (((firstName.isEmpty() || lastName.isEmpty()) || (dob.isEmpty() || address.isEmpty() || phone.isEmpty())) || (email.isEmpty())){
           int warning = JOptionPane.showConfirmDialog(null, "Enter missing values.", "Warning",
            JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
        }
               
        else {
                    
        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Edit this patron's details?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        // close dialog if no
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.getRootFrame().dispose();
            
        // edit the patron if yes
        } else if (response == JOptionPane.YES_OPTION) {
            
            // compare IDs
            String compareID = jTextEditPatID.getText();
            if (!(compareID.equals(patronID))){
                int warning = JOptionPane.showConfirmDialog(null, "You cannot change an existing ID.", "Warning",
            JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
                
            }
        
            else {
                 // give user a chance to add a new record with the id entered      
        if (status == 1){
                insertEditPatron = "INSERT INTO patron(patron_id) VALUES(" + id + ")";
                stmt.executeUpdate(insertEditPatron);
                status = 0;
            } 
        // update the record
        //stmt.executeUpdate(editPatron);
        pStmt = conn.prepareStatement(editPatron);
        pStmt.setString(1, firstName);
        pStmt.setString(2, initial);
        pStmt.setString(3, lastName);
        pStmt.setString(4, dob); 
        pStmt.setString(5, gender);
        pStmt.setString(6, address);
        pStmt.setString(7, email);
        pStmt.setString(8, phone);    
        pStmt.setString(9, patronID);
        
        pStmt.executeUpdate();
        conn.close();
            }
        
        
        } 
            
        }  
        
        }catch(SQLException se){}
        
    }//GEN-LAST:event_jButtonEditSaveActionPerformed

    private void jButtonEditClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClearActionPerformed
        // TODO add your handling code here:
        firstName = ""; 
     initial = "";
     lastName = "";
     address = "";
     dob = "";
     gender = "";
     email = "";
     phone = "";
     
     //jTextEditPatID.setText("");
     jTextEditFirstName.setText("");
     jTextEditInitial.setText("");
     jTextEditLastName.setText("");
     jFormattedEditDOB.setText("");
     jTextEditAddress.setText("");
     jTextEditEmail.setText("");
     jTextEditPhone.setText("");
    }//GEN-LAST:event_jButtonEditClearActionPerformed

    private void jButtonDeleteSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSearchActionPerformed
        // TODO add your handling code here:
        // Search for a record to delete
        
        jTextDeleteFirstName.setText("");
        jTextDeleteInitial.setText("");
        jTextDeleteLastName.setText("");
        jFormattedDeleteDOB.setText("");
        jTextDeleteAddress.setText("");
        jTextDeleteEmail.setText("");
        jTextDeletePhone.setText("");
        
        try{
        Class.forName(JDBC_DRIVER);
        }catch(ClassNotFoundException e){}
        try{
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        stmt = conn.createStatement();
        patronID = jTextDeletePatID.getText();
        
        
        //warn user if ID has not been entered
        if(patronID.isEmpty()){ 
           int warning = JOptionPane.showConfirmDialog(null, "Please enter an ID.", "Attention.",
            JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
        }
        else{
                
        search = "SELECT * FROM patron WHERE patron_id = " + patronID + " ";
        ResultSet rs = stmt.executeQuery(search);
        
        while(rs.next()){
        jTextDeleteFirstName.setText(rs.getString("first_name"));
        jTextDeleteInitial.setText(rs.getString("initial"));
        jTextDeleteLastName.setText(rs.getString("last_name"));
        
        
        // Change date format
        DateFormat df;
            df = new SimpleDateFormat("yyyy-MM-dd");
        dob = df.format(rs.getDate("dob"));
        if (dob.isEmpty() || dob == null){
            jFormattedDeleteDOB.setText("");
        } else{
        jFormattedDeleteDOB.setText(dob);
        }
        
        jComboBoxDeleteGender.setSelectedItem(rs.getString("gender"));
        jTextDeleteAddress.setText(rs.getString("address"));
        jTextDeleteEmail.setText(rs.getString("email"));
        jTextDeletePhone.setText(rs.getString("phone")); 
        
        } // end while
        
        
        String test = jTextDeleteFirstName.getText();
        if(test.isEmpty()){ 
           int warning = JOptionPane.showConfirmDialog(null, "No record found.", "Attention.",
            JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
                     
        }
        
        
        
        }
        conn.close();
        
        
        }catch(SQLException se){}
    }//GEN-LAST:event_jButtonDeleteSearchActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        patronID = jTextDeletePatID.getText();
        int id = Integer.parseInt(patronID);
        
        deletePatron = "DELETE FROM patron WHERE patron_id = " + id ;
        try{
        Class.forName(JDBC_DRIVER);
        }catch(ClassNotFoundException e){}
        try{
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        stmt = conn.createStatement();
        
        // Prompt the user
        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = JOptionPane.showConfirmDialog(null, "Delete this patron?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        // close dialog if no
        if (response == JOptionPane.NO_OPTION) {
            JOptionPane.getRootFrame().dispose();
            
        // add book if yes
        } else if (response == JOptionPane.YES_OPTION) {
        
        // insert the record
        stmt.executeUpdate(deletePatron);
        
        
        // clear the text fields - use a method
        jTextDeletePatID.setText("");
        jTextDeleteFirstName.setText("");
        jTextDeleteInitial.setText("");
        jTextDeleteLastName.setText("");
        jFormattedDeleteDOB.setText("");
        jTextDeleteAddress.setText("");
        jTextDeleteEmail.setText("");
        jTextDeletePhone.setText("");
         
        conn.close();
        }  
          
        }catch(SQLException se){}
    
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatronsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatronsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatronsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatronsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            PatronsMenu dialog = new PatronsMenu(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPatron;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDeleteSearch;
    private javax.swing.JButton jButtonEditClear;
    private javax.swing.JButton jButtonEditSave;
    private javax.swing.JButton jButtonEditSearch;
    private javax.swing.JComboBox<String> jComboBoxDeleteGender;
    private javax.swing.JComboBox<String> jComboBoxEditGender;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JFormattedTextField jFormattedDeleteDOB;
    private javax.swing.JFormattedTextField jFormattedEditDOB;
    private javax.swing.JFormattedTextField jFormattedTextDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextDeleteAddress;
    private javax.swing.JTextField jTextDeleteEmail;
    private javax.swing.JTextField jTextDeleteFirstName;
    private javax.swing.JTextField jTextDeleteInitial;
    private javax.swing.JTextField jTextDeleteLastName;
    private javax.swing.JTextField jTextDeletePatID;
    private javax.swing.JTextField jTextDeletePhone;
    private javax.swing.JTextField jTextEditAddress;
    private javax.swing.JTextField jTextEditEmail;
    private javax.swing.JTextField jTextEditFirstName;
    private javax.swing.JTextField jTextEditInitial;
    private javax.swing.JTextField jTextEditLastName;
    private javax.swing.JTextField jTextEditPatID;
    private javax.swing.JTextField jTextEditPhone;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextInitial;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextPhone;
    // End of variables declaration//GEN-END:variables
}
